@ApiUrl = https://localhost:7001/api/v1/students
@StudentId = 1


### Get all Students
GET {{ApiUrl}}
Accept: application/json

### Get a Student by ID
GET {{ApiUrl}}/{{StudentId}}
Accept: application/json

### Create a new Student
POST {{ApiUrl}}
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com"
}

### Update a Student by ID
PUT {{ApiUrl}}/{{StudentId}}
Content-Type: application/json

{
  "name": "John Doe II",
  "email": "john.doe@gmail.com"
}

### Delete a Student by ID
DELETE {{ApiUrl}}/{{StudentId}}
