@ApiUrl = https://localhost:7001/api/v1/course-instances
@CourseId = 1
@StudentId = 2
@StartDate = 2025-10-27
@EndDate = 2025-12-31
@CourseInstanceId = 4


### Get all Course Instances
GET {{ApiUrl}}
Accept: application/json

### Get Course Instance by ID
GET {{ApiUrl}}/{{CourseInstanceId}}
Accept: application/json

### Get Courses by Student ID
GET {{ApiUrl}}/students/{{StudentId}}/courses
Accept: application/json

### Get Courses by Date Range
GET {{ApiUrl}}/courses?startDate={{StartDate}}&endDate={{EndDate}}
Accept: application/json

### Create Course Instance
POST {{ApiUrl}}
Content-Type: application/json

{
  "startDate": "{{StartDate}}",
  "endDate": "{{EndDate}}",
  "courseId": {{CourseId}},
  "studentIds": [
    1,
    2,
    3
  ]
}

### Update Course Instance
PUT {{ApiUrl}}/{{CourseInstanceId}}
Content-Type: application/json

{
  "startDate": "{{StartDate}}",
  "endDate": "{{EndDate}}",
  "courseId": {{CourseId}},
  "studentIds": [
    1,
    2
  ]
}

### Delete Course Instance
DELETE {{ApiUrl}}/{{CourseInstanceId}}
