@ApiUrl = https://localhost:7001/api/v1/auth
@Email = john.doe@example.com
@Password = YourSecurePassword123!


### Register a new user
POST {{ApiUrl}}/register
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}

### Login user
POST {{ApiUrl}}/login
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}
